name: test-action
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - run: npm install
      - run: npm run build

      - name: Deploy with Rsync
        uses: shimataro/ssh-key-action@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: avzn
          SOURCE: "./dist"
          TARGET: "/home/zellwk/zellwk.com/dist"
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}

